"""add store_name to shopping_lists

Revision ID: 43a4288e970a
Revises: cc8f0f28313b
Create Date: 2026-03-10 01:26:46.179630
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43a4288e970a'
down_revision: Union[str, None] = 'cc8f0f28313b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopping_lists', sa.Column('store_name', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopping_lists', 'store_name')
    # ### end Alembic commands ###
