"""add icon column to events

Revision ID: 43aa8f49e954
Revises: 440abfeafea8
Create Date: 2026-03-09 15:01:56.788896
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43aa8f49e954'
down_revision: Union[str, None] = '440abfeafea8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('icon', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'icon')
    # ### end Alembic commands ###
